MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  # Initial weight to load from image-caption training
  WEIGHT: ""
  # Trim the prefix of the checkpoint parameter names so they can be correctly loaded
  BACKBONE_PREFIX: "backbone.body."
  # Set true when resuming training. Otherwise should be False to prevent loading trainer
  # state from pretraining phase.
  LOAD_TRAINER_STATE: False
  # Always true for zero-shot settings, although it is false for regular Faster R-CNN
  # If false, it learns a bounding box regression for each (seen) class separately
  CLS_AGNOSTIC_BBOX_REG: True
  ROI_BOX_HEAD:
    # Note these are the number of classes for training only
    NUM_CLASSES: 49
    # Dimension of embeddings that will be loaded
    EMB_DIM: 512
    # Always true for zero-shot
    EMBEDDING_BASED: True
    # To balance background proposals vs. foreground. Especially important to tune for
    # zero-shot settings, because a value too large would push unseen classes to background.
    LOSS_WEIGHT_BACKGROUND: 0.2
    # Whether or not to freeze the vl_projection layer. True is better.
    FREEZE_EMB_PRED: True
  ROI_HEADS:
    # At most how much of a batch should be filled with positive boxes. In zero-shot setting
    # having too many background hurts. Note 1.0 doesn't mean there won't be any background.
    # It is unlikely to have 512 positive boxes, and the rest is always filled with background.
    POSITIVE_FRACTION: 1.0
  BACKBONE:
    FREEZE_CONV_BODY_AT: 2
DATASETS:
  TRAIN: ("coco_zeroshot_train",)
  TEST: ("coco_generalized_zeroshot_val",)
  DATASET_CLASS: "COCODataset"
  DATASET_ARGS:
    LOAD_EMBEDDINGS: True
    # The key for embedding to load.
    EMB_KEY: "ClipEmb"
    # Dimension of embeddings
    EMB_DIM: 512
SOLVER:
  BASE_LR: 0.0005
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 120000)
  MAX_ITER: 150000
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 10000
  TEST_PERIOD: 2500
  LOG_PERIOD: 100
  SKIP_VAL_LOSS: True # val loss is not correct, to be deleted
TEST:
  IMS_PER_BATCH: 8
