alpha: 0.4
batch_size: 2
bert_config: configs/config_bert.json
embed_dim: 256
image_res: 256
mlm_probability: 0.15
momentum: 0.995
optimizer: {lr: 0.0001, opt: adamW, weight_decay: 0.02}
queue_size: 65536
schedular: {cooldown_epochs: 0, decay_rate: 1, epochs: 30, lr: 0.0001, min_lr: 1e-05,
  sched: cosine, warmup_epochs: 20, warmup_lr: 1e-05}
temp: 0.07
train_file: [examples/image_caption_final.json]
vision_width: 768
